### ISSUE TITLE
Gate::URL_SUBSCRIBED_APPS

### ISSUE THREAD

**Issue by andersborgabiro** [Fritak/messenger-platform#1]
Is used as Gate::SUBSCRIBED_APPS in MessengerPlatform, hence undefined.

I can't say it worked better after that, as subscribe and getMessagesReceived return false despite correct Page access token and Webhook token.

The script is no doubt called when entering messages. I just don't get any message data. I've used example.php and checked the documentation. All applicable permissions are set in the console.

Please let me know if you've succeeded with basic interactions.

Cheers,
Anders

**Comment by Fritak** [comment]
That could be problem with curl, please check if you are subscribed - in v1.0.3 it should throw curl exception, if is any error there. 

Calling are SSL, so you have to double check that.

**Comment by andersborgabiro** [comment]
I got it working. I did buggy logging of the results :).
