### ISSUE TITLE
FatalError Exception

### ISSUE THREAD

**Issue by deios0** [Fritak/messenger-platform#10]
`Symfony\Component\Debug\Exception\FatalErrorException: Cannot redeclare fritak\MessengerPlatform\Messaging::$delivery in ../vendor/fritak/messenger-platform/source/MessageReceived.php:60`

**Comment by deios0** [comment]
You declare $delivery twice

`    /*\* @var fritak\MessengerPlatform\Message Message. */
    public $message;

```
/** @var fritak\MessengerPlatform\Delivery Message. */
public $delivery;

/** @var fritak\MessengerPlatform\Delivery Message. */
public $delivery;

public function __construct($data)`
```

**Comment by Fritak** [comment]
Yeah, that was fixed https://github.com/Fritak/messenger-platform/commit/6cf4954e3062366f36c6421982ad79ab65ef5e4c .
