### ISSUE TITLE
Getting NULL in message->text

### ISSUE THREAD

**Issue by deios0** [Fritak/messenger-platform#11]
Could you please check, I get 'NULL' in message text:

`$messages = $bot->getMessagesReceived();

```
        if (count($messages) > 0)

            foreach ($messages as $message) {

                $item = $message->messaging[0];
                $sender = $item->sender->id;

                if (isset($item->message)) {

                    $text = $item->message->text;
                    $response = $this->processTheText($text);`
```

**Comment by Fritak** [comment]
Do you have request for that? If it is POSTBACK then is text null.

**Comment by deios0** [comment]
No, it's not a postback, I checked it. The request is:

`[2016-04-19 09:08:46] FB-Messenger-Bot-Logger.INFO: NEW REQUEST  ["{\"object\":\"page\",\"entry\":[{\"id\":830113327037526,\"time\":1461071136095,\"messaging\":[{\"sender\":{\"id\":818329708271522},\"recipient\":{\"id\":830113327037526},\"timestamp\":1461071136064,\"message\":{\"mid\":\"mid.1461071136056:a2a61d0c01286f4545\",\"seq\":249,\"text\":\"test\"}}]}]}",[]] []`

**Comment by deios0** [comment]
Postback works fine, btw

**Comment by Fritak** [comment]
It should work now.

**Comment by Fritak** [comment]
I definitely have to write some tests.

**Comment by deios0** [comment]
Yes, works, thank you
