### ISSUE TITLE
sendMessage doesn't send anything back

### ISSUE THREAD

**Issue by andersborgabiro** [Fritak/messenger-platform#13]
I very much appreciate your effort, but for each patch it still doesn't work somewhere else, so I'm switching to a much simpler solution (https://github.com/TommyBs/FBPHPMessengerBot). This very simple code worked immediately for text-only chat, which is what I need right now.

I doubt there's so much difference between PHP 5.5.9 and 5.6 that it would break the code.

Also a general advice is to not abstract the code so much. Verifying the Webhook is just this:

```
if (isset($_GET['hub_verify_token'])):
    if ($verify_token == $_GET['hub_verify_token']):
        echo $_GET['hub_challenge'];
        exit();
    endif;
endif;
```

This is 100% correct code, and there's no need for several levels of abstractions for such a simple thing.

Regards,
Anders

**Comment by Fritak** [comment]
Thank you. Of course please use what suit you best. This code was intended mainly for my use, but why not share it with world? :) I caught a lot of bugs, so yay, hooray.

I like abstracting the code, but you don't have to. Screwdriver work fine, why consider use of drill? Your example work fine. Or you can use:

```
if ($bot->request->isSubscribe())
{
    if ($bot->request->verifyWebhookToken($webhookToken)):
        $bot->request->getChallenge();
        exit;
    }
}
```

Btw do you know what is dependencies injection and MVC? You can inject bot somewhere, then you don't need to inject config with verify token. Or even read request.

So in my eyes it is not valid argument. If you wish you can do it many ways. But as I said, please use what suit you best.

**Comment by andersborgabiro** [comment]
This is off-topic, but related:

Have you also experienced that sending buttons don't work at all (whatever code is used).

I had no problem sending images via URL or images via file, but e.g. the following is simply ignored by Facebook, despite being correct according to the documentation. I set content-type correctly too. Anything you've seen?

```
{
    "recipient": {
        "id": "---------------------------"
    },
    "message": {
        "attachment": {
            "type": "template",
            "payload": {
                "template_type": "button",
                "text": "Where do you want to go?",
                "buttons": [
                    {
                        "type": "web_url",
                        "title": "Abiro",
                        "url": "http:\\/\\/abiro.com"
                    },
                    {
                        "type": "web_url",
                        "title": "CliqTags",
                        "url": "http:\\/\\/cliqtags.com"
                    },
                    {
                        "type": "web_url",
                        "title": "Twitizer",
                        "url": "http:\\/\\/twitizer.com"
                    },
                    {
                        "type": "web_url",
                        "title": "Google",
                        "url": "http:\\/\\/google.com"
                    }
                ]
            }
        }
    }
}
```

**Comment by andersborgabiro** [comment]
I solved the button problem: It only allows up to 3 buttons. Go figure.
