### ISSUE TITLE
No messages received

### ISSUE THREAD

**Issue by Matthiasvt** [Fritak/messenger-platform#14]
Hi,

I have an issue that is driving me nuts, hope you know how to fix it.

I've used your library and pimax's one while trying to get a response when sending a message from messenger to the bot.

The strange thing is that I can see that Facebook is sending to the webhook but the request stays empty.

Some notes:
SSL certificate is fine (EV).
PHP 5.5.
Token is verified & page is linked.
Subscribed to the page.

I ran out of options after hours of trying. Hopefully you have some last idea's.

**Comment by Fritak** [comment]
Just to be clear are you reading read-only stream input? _php://input_
http://php.net/manual/en/wrappers.php.php

**Comment by Matthiasvt** [comment]
Yeah I am.

I found an issue that seems related to mine: http://stackoverflow.com/questions/36657366/messenger-bot-in-php-no-response-back#_=_

**Comment by Matthiasvt** [comment]
nvm, thx for your help found the issue, rookie mistake..
