### ISSUE TITLE
Error with complex message 2

### ISSUE THREAD

**Issue by ringfinger** [Fritak/messenger-platform#15]
Hi,
I have an error when I try to send complex message 2, here is the code:

```
$responseMessage = new StructuredMessage($messaging['sender']['id'],
                            [new Element('Example.', 'Example...', 'http://placehold.it/150x150', 'http://placehold.it/150x150', [new Button('Click', Button::TYPE_WEB, 'example.com')])],
                            MessageSend::NOTIFICATION_TYPE_SILENT_PUSH,
                            StructuredMessage::ATTACHMENT_TYPE_TEMPLATE,
                            StructuredMessage::TEMPLATE_PAYLOAD_TYPE_GENERIC);


                        $bot = $this->init_bot();
                        $bot->sendComplexMeesage($responseMessage);
```

Error message:
`ERROR: exception 'FatalErrorException' with message 'Call to a member function getDataForCall() on array' in fritak/messenger-platform/source/StructuredMessage.php:68`

Text message and complex message 1 & 3 work fine for me.

**Comment by Fritak** [comment]
It should be fine now. Could you please try send message?

**Comment by ringfinger** [comment]
No error now. I can receive the complex message 2 now.
However, I cannot see the image in the message.
![screenshot from 2016-04-27 12 45 16](https://cloud.githubusercontent.com/assets/18341796/14842018/006a680e-0c76-11e6-9531-319f62f02289.png)
