### ISSUE TITLE
Acknowledge/Confirmation of Messages Received 

### ISSUE THREAD

**Issue by michelpf** [Fritak/messenger-platform#19]
Using your example, make some comments, I was able to receive messages, but when I triggered an action, seems to be entered in loop or something. Searching for other implementers, they always explain to send and answer code 200, to confirm the receive os messages. Could you check what is missing in my code?

$messages = $bot->getMessagesReceived();

for ($j=0;$j<sizeof($messages[0]->messaging);$j++){
    $userToSendMessage =  $messages[0]->messaging[$j]->sender->id;
    if ( $messages[0]->messaging[$j]->message == "1"){
        $bot->sendMessage($userToSendMessage, 'ritgh!');
    }
    else
    {
        $bot->sendMessage($userToSendMessage, 'wrong!');
    }
}

After send any message, thru the Messenger App, I receive, with no stop, lot's of "wrong" messages. To make it stop, I need to comment the sendMessage in PHP file.

The key is, after processed the messages received, there is some kind of confirmation to send?
Thanks in advance and congratulations for your remarkable work!

**Comment by achimha** [comment]
You also get delivery confirmations so don't respond unless you get a message from the user to avoid the feedback loop.

**Comment by Fritak** [comment]
Yes, facebook is sending confirmation "message". So, if delivery (\fritak\MessengerPlatform\Delivery) is not empty, simply don't send anything back. 

see here: https://developers.facebook.com/docs/messenger-platform/webhook-reference#message_delivery

**Comment by michelpf** [comment]
Based on my code, what I should do? Just get the Delivery is enought to confirm?

$mids= $messages[0]->messaging[$j]->delivery->mids[0];

Is anything better?

**Comment by michelpf** [comment]
Solve using that

if (!empty($message)){
    $bot->sendMessage($user, $message);
}   

Thank you guys!
