### ISSUE TITLE
Recipient handling is broken

### ISSUE THREAD

**Issue by andersborgabiro** [Fritak/messenger-platform#4]
It's impossible to send anything with "-master" due to wonky handling of the recipient (probably in getRecipient).

I reverted to previous code, and it works with that. I only use sendMessage in the current implementation.

This is how I extract and use relevant data, as a reference:

```
if ($messages):
    foreach ($messages as $message):
        $item = $message->messaging[0];
        $sender = $item->sender->id;
        $text = $item->message->text;
        $response = processTheText($text);
        $bot->sendMessage($sender, $response);
    endforeach;
endif;
```

Facebook complains that the Webhook can't be verified. Have you tested that?

**Comment by Fritak** [comment]
What version of php do you use? It is working fine for me in _5.6.11_

**Comment by andersborgabiro** [comment]
5.5.9. I'll check if I can upgrade.

is_numeric($sender) seemed to fail, but I'll test again later today.

**Comment by andersborgabiro** [comment]
5.5.9 is the latest version shipped for Ubuntu, so I'll have to stay there for now.

I found a much simpler solution to my needs, that's currently only text in / text out.

I'd like to use your library in the future though, but no panic :).

**Comment by Fritak** [comment]
Fixed in last version.
