### ISSUE TITLE
The error on composer update

### ISSUE THREAD

**Issue by deios0** [Fritak/messenger-platform#6]
PHP Parse error:  Invalid numeric literal in /var/www/unicornbay.com/vendor/fritak/messenger-platform/example.php on line 19

Parse error: Invalid numeric literal in /var/www/unicornbay.com/vendor/fritak/messenger-platform/example.php on line 19

**Comment by Fritak** [comment]
Numbers starting with 0 are octal literals. That number is not a valid octal literal, so you get an error. But that is just an example.

**Comment by deios0** [comment]
It's true, but I'm getting an error on my composer update:

`Loading composer repositories with package information
Updating dependencies (including require-dev)
- Removing fritak/messenger-platform (v1.1.1)
- Installing fritak/messenger-platform (v1.1.2)
  Loading from cache

Writing lock file
Generating autoload files

PHP Parse error:  Invalid numeric literal in .../vendor/fritak/messenger-platform/example.php on line 19
Parse error: Invalid numeric literal in .../vendor/fritak/messenger-platform/example.php on line 19'

**Comment by deios0** [comment]
So I need to manually edit this file and comment out line 19.

**Comment by Fritak** [comment]
I changed example, it should be okay now.

**Comment by deios0** [comment]
Works, thank you!
