### ISSUE TITLE
Implementation of getMessagesReceived

### ISSUE THREAD

**Issue by usamanoman** [Fritak/messenger-platform#7]
You example file is all code in one file, and facebook documentation separates GET and POST webhooks. Can you please point me the implementation of getMessagesReceived ? So I can see my message in Webhook post call?

I am trying to integrate your package with "Laravel" I have subscribed my application however still not being able to receive messages.

**Comment by Fritak** [comment]
Have you properly set request in constructor of bot?  

You are getting messages in ParseRequest::getMessagesReceived() so if it is message it should be there.
