### ISSUE TITLE
Must I get the pages_messaging approved?

### ISSUE THREAD

**Issue by sxwei123** [Fritak/messenger-platform#8]
Now the GET of hook work for me. But the I cannot get the POST data when I send message to my page via Messenger App. So I am wondering Must I get the pages_messaging approved first so that I can receive the message?

**Comment by Fritak** [comment]
If you are admin of that page, it should be fine. But you have to subscribe page to receive messages.

**Comment by sxwei123** [comment]
I exec this:
curl -ik -X POST "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token=<token>"
according to the document. And I got:
{"success": true}
Is this mean I have subscribe successfully and I don't need to subscribe again?

**Comment by Fritak** [comment]
Yeah, this should work just fine. There were some issues with messages, could you try please latest version (v1.1.7)?

**Comment by sxwei123** [comment]
Actually I am quiet new to PHP.
Can you write a simple echo bot so that I can understand your code?
