### ISSUE TITLE
Webhooks Page Subscription  Issue

### ISSUE THREAD

**Issue by knowledgecorner** [Fritak/messenger-platform#9]
Hi,
Unable to subscribe  I am using the "messenger-platform"  executing the example.php file 
passing the accessToken = my page access token and  webhookToken="Verify Token"

but getting Error like : "The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 500; HTTP Message = Internal Server Error"

please find the image : https://sri-knowledgecorner.rhcloud.com/webhook_messanger.png

**Comment by Fritak** [comment]
Could you please post your code? You can't just use example, you need to edit him at least a little bit.

**Comment by knowledgecorner** [comment]
<?php
use fritak\MessengerPlatform\Button;
use fritak\MessengerPlatform\Element;
use fritak\MessengerPlatform\MessageSend;
use fritak\MessengerPlatform\StructuredMessage;
use fritak\MessengerPlatform\UserRecipient;

use fritak\MessengerPlatform\ReceiptElement;
use fritak\MessengerPlatform\Receipt;
use fritak\MessengerPlatform\Summary;
use fritak\MessengerPlatform\Address;
use fritak\MessengerPlatform\Adjustment;

require_once(dirname(**FILE**) . '/vendor/autoload.php');

$stream  = file_get_contents("php://input");
$request = empty($stream)? $_REQUEST : $stream;
$bot = new \fritak\MessengerPlatform(
        ['accessToken'      => 'here i can place page access token',
         'webhookToken'     => 'here i can place page Verify Token',
         'facebookApiUrl'   => 'https://graph.facebook.com/v2.6/me/'
        ], $request);

if($bot->checkSubscribe())
{
    print $bot->request->getChallenge();
    exit;
}

Little bit confusion about  "accessToken"  , what can I  pass to accessToken  means App id  or page accesstoken ?

**Comment by Fritak** [comment]
Page access token, https://developers.facebook.com/docs/messenger-platform/implementation#page_access_token

**Comment by knowledgecorner** [comment]
I am using  page access token  but  unable to handle ,
creat a new file boot.php and put the code like 

$challenge = $_REQUEST['hub_challenge'];
$verify_token = $_REQUEST['hub_verify_token'];
if ($verify_token === 'Yapyzal_staging_server') {
echo $challenge;
}
This code working fine ...
but how can i handle your example file

**Comment by Fritak** [comment]
Do you have latest version? What version PHP do you use?

**Comment by knowledgecorner** [comment]
PHP  5.6

**Comment by knowledgecorner** [comment]
This file not included 
echo require_once(dirname(**FILE**) . '/vendor/autoload.php'); nothing to display in this file just comment the return "return ComposerAutoloaderInit304c70e3a9fe78bbc8b5b092ab75ab50::getLoader();" , it will display 1 ,
how to achieve this

**Comment by Fritak** [comment]
And do you have latest version of this library?

**Comment by knowledgecorner** [comment]
1.1.3 version

**Comment by Fritak** [comment]
Please try latest, it should work.

**Comment by knowledgecorner** [comment]
latest version is v1.1.8 is it right ?

**Comment by Fritak** [comment]
Yes.

**Comment by knowledgecorner** [comment]
Thank you for support , Subscription completed successfully with latest version v1.1.8, but 
$messages=$bot->getMessagesReceived();
it not return any thing how to get senderid ? can you explain please.

**Comment by knowledgecorner** [comment]
Hi ,
I got it  $userToSendMessage = $messages[0]->messaging[0]->sender->id; ,
$bot->sendMessage($userToSendMessage, 'Hi Sri!'); continuously sending messages,
what i missed.

**Comment by Fritak** [comment]
We don't know yet, but this code before sending/receiving message:  `$bot->subscribe();` should prevent multiple sending, because facebook keep calling you.

**Comment by knowledgecorner** [comment]
Yes  one of reason and we need to verify  if the messages send are empty
if(!empty($messages[0]->messaging[0]->message)){
  $bot->sendMessage($userToSendMessage, 'Hi Fritak how are you!');
}
its prevent multiple sending.

**Comment by knowledgecorner** [comment]
I Really Appreciate for spontaneous  Respond and Support , Its great Effort.
Thanks once again.

**Comment by sxwei123** [comment]
Every time you send a message, Messenger will send you a message-delivered callback:
https://developers.facebook.com/docs/messenger-platform/webhook-reference#message_delivery
That's why you always get empty message.

**Comment by somendraraj** [comment]
getting this error when trying to verify webhooks can you please tell me what is the root cause?

The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 405; HTTP Message = Method Not Allowed
